server:
  port: 9091
spring:
  application:
    name: logging-admin-sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/test

logging:
  level:
    org.minbox.framework.logging.admin: debug